# Generated by Django 2.2.7 on 2019-12-04 08:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('footage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footage',
            options={'verbose_name_plural': 'Footage'},
        ),
        migrations.AddField(
            model_name='footage',
            name='file_loc',
            field=models.CharField(default=datetime.datetime(2019, 12, 4, 8, 1, 48, 103705, tzinfo=utc), max_length=100, verbose_name='File Location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footage',
            name='upload_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
