# Generated by Django 2.2.7 on 2019-12-04 08:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('footage', '0003_footage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footage',
            name='id',
        ),
        migrations.AddField(
            model_name='footage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
