# Generated by Django 2.2.7 on 2019-12-04 08:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('footage', '0005_auto_20191204_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
