# Generated by Django 2.2.7 on 2019-12-04 08:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('footage', '0006_auto_20191204_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footage',
            options={'verbose_name_plural': 'Clips'},
        ),
        migrations.AddField(
            model_name='footage',
            name='key',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='footage',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
