# Generated by Django 2.2.7 on 2019-12-04 08:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('footage', '0007_auto_20191204_0852'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Footage',
            new_name='File',
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name_plural': 'Files'},
        ),
    ]
