# Generated by Django 2.2.7 on 2019-12-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footage', '0008_auto_20191204_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_loc',
        ),
        migrations.AddField(
            model_name='file',
            name='footage_file',
            field=models.FileField(default=None, upload_to='footage/'),
            preserve_default=False,
        ),
    ]
